version: '3'
services:

  wtf_backend_postgres:
    container_name: wtf_backend_postgres
    image: 'postgres:latest'
    env_file:
      - ./.env
    # ports:
    #   - 5432:5432
    volumes:
      - ./pg:/var/lib/postgresql/data
    networks:
      wtf_backend_postgres_net:
        ipv4_address: 172.222.0.10

networks:
  wtf_backend_postgres_net:
    name: wtf_backend_postgres_net
    ipam:
      config:
        - subnet: "172.222.0.0/16"